name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set image version
        required: true

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}
  DISCORD: ${{ secrets.DISCORD_WEBHOOK }}
  VERSION: ${{ github.event.inputs.version }}

jobs:
  push_docker_image_to_dockerhub:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Build and push with tag latest
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: moleszek/ansible:latest
      - name: Build and push with tag ${{ env.VERSION }}
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: moleszek/ansible:${{ env.VERSION }}
  notify_on_success:
    name: Send notification on success
    needs:
      - push_docker_image_to_dockerhub
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully built and push docker image to DockerHub!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - push_docker_image_to_dockerhub
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          status: failure
          description: "Failed to build and push docker image to DockerHub!"
