name: Docker registry
on:
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}
  DISCORD: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  push_docker_image_to_dockerhub:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ${{ github.repository }} repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        token: ${{ secrets.token }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASS }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: moleszek/ansible:latest
  notify_on_success:
    name: Send notification on success
    needs:
      - push_docker_image_to_dockerhub
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Successfully built and pushed docker image do DockerHub!"
  notify_on_failure:
    name: Send notification on failure
    needs:
      - push_docker_image_to_dockerhub
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ env.DISCORD }}
          description: "Failed to build and pushed docker image do DockerHub!"
