name: Docker registry
on:
  workflow_dispatch:
    inputs:
      version:
        description: Set image version
        required: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  push_docker_image_to_dockerhub:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}

      - name: Build and push with tag latest
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: moleszek/ansible:latest

      - name: Build and push with tag ${{ env.VERSION }}
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: moleszek/ansible:${{ env.VERSION }}

      - name: Build and push to GitHub Container with tag latest
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/solairen/docker_ansible/ansible:latest
          secrets: |
              GIT_AUTH_TOKEN=${{ secrets.token }}

      - name: Build and push to GitHub Container with tag ${{ env.VERSION }}
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/solairen/docker_ansible/ansible:${{ env.VERSION }}
          secrets: |
              GIT_AUTH_TOKEN=${{ secrets.token }}