name: Test docker image
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches-ignore:
      - "main"

jobs:
  test:
    name: Test-build Docker image
    runs-on: ubuntu-latest
    container: docker:stable
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push with tag latest
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: false
          tags: moleszek/ansible:latest